services:
  db:
    image: postgres:17
    container_name: postgres_docker
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shelves_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d  # folder chứa các script SQL
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=han.tran@eggstech.io"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
  app:
    build: .
    image: flask_vertex_app
    container_name: flask_vertex_container
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: shelves_db
      PORT: 6000
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcv_key.json
    command: python app.py
    restart: unless-stopped
    ports:
      - "6000:6000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./gcv_key.json:/app/gcv_key.json:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yolo-app.rule=Host(`ip.aeon.metatek.okayla.vn`)"
      - "traefik.http.routers.yolo-app.entrypoints=websecure"
      - "traefik.http.routers.yolo-app.tls=true"
      - "traefik.http.routers.yolo-app.tls.certresolver=myresolver"
      - "traefik.http.services.yolo-app.loadbalancer.server.port=6000"
volumes:
  db_data: