services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=han.tran@eggstech.io"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  yolo-app:
    build: .
    image: demo-yolo8
    container_name: yolo_app
    volumes:
      - .:/app
    environment:
      - PORT=8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yolo-app.rule=Host(`ip.aeon.metatek.okayla.vn`)"
      - "traefik.http.routers.yolo-app.entrypoints=websecure"
      - "traefik.http.routers.yolo-app.tls=true"
      - "traefik.http.routers.yolo-app.tls.certresolver=myresolver"
      - "traefik.http.services.yolo-app.loadbalancer.server.port=8000"
    command: python app.py
    restart: unless-stopped
