services:
  db:
    image: postgres:17
    container_name: postgres_docker
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shelves_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d  # folder chứa các script SQL

  app:
    build: .
    image: flask_vertex_app
    container_name: flask_vertex_container
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: shelves_db
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcv_key.json
    command: python app.py
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./gcv_key.json:/app/gcv_key.json:ro

volumes:
  db_data: